name: ml-zoomcamp
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter
  - cudatoolkit
  - tensorflow=2.4.3
  - numpy=1.21.1
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn=0.11.2
  - xgboost

