apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mlzoomcamp-eks
  region: eu-west-1
  version: "1.21"

nodeGroups:
  - name: ng
    desiredCapacity: 2
    instanceType: m5.xlarge
